const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const W=canvas.width,H=canvas.height;
const ui={wave:document.getElementById('wave'),gold:document.getElementById('gold'),hp:document.getElementById('hp'),start:document.getElementById('startWave'),volley:document.getElementById('volley'),frost:document.getElementById('frost'),message:document.getElementById('message')};
let gold=100, hp=100, wave=1, running=false, waveTotal=0, spawnLeft=0, spawnTimer=0, last=0, frostTime=0, shake=0;
const towers=[], zombies=[], arrows=[], effects=[];
const path=[{x:-30,y:300},{x:160,y:300},{x:245,y:210},{x:390,y:210},{x:485,y:330},{x:635,y:330},{x:735,y:205},{x:990,y:205}];
const pads=[{x:100,y:420},{x:190,y:150},{x:330,y:340},{x:410,y:135},{x:550,y:455},{x:665,y:430},{x:790,y:320},{x:835,y:135}];
function setMessage(t){ui.message.textContent=t;}
function updateUI(){ui.gold.textContent=gold;ui.hp.textContent=hp;ui.wave.textContent=wave;ui.volley.disabled=gold<40||!running;ui.frost.disabled=gold<30||!running;}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function pathPoint(z){let a=path[z.segment],b=path[z.segment+1]; return {x:a.x+(b.x-a.x)*z.t,y:a.y+(b.y-a.y)*z.t};}
function startWave(){if(running)return;running=true;waveTotal=5+wave*3;spawnLeft=waveTotal;spawnTimer=0;setMessage('Wave '+wave+' incoming. Keep the path clear!');updateUI();}
function spawn(){let tough=wave>2&&Math.random()<.15;zombies.push({x:path[0].x,y:path[0].y,segment:0,t:0,hp:tough?55+wave*8:30+wave*5,max:tough?55+wave*8:30+wave*5,speed:tough?21:29+wave*1.5,r: tough?16:12,slow:0,hit:0});spawnLeft--;}
function recruit(p){if(p.tower||gold<50)return;gold-=50;p.tower={x:p.x,y:p.y,cool:0,level:1};towers.push(p.tower);setMessage('Archer recruited. Build another tower or start the wave.');updateUI();}
function useVolley(){if(gold<40||!running)return;gold-=40;zombies.forEach(z=>{z.hp-=25+wave*2;effects.push({x:z.x,y:z.y,type:'burst',life:.45})});shake=7;setMessage('VOLLEY! Every zombie has been struck.');updateUI();}
function useFrost(){if(gold<30||!running)return;gold-=30;frostTime=5;zombies.forEach(z=>z.slow=5);effects.push({x:480,y:300,type:'frost',life:1});setMessage('Frost trap triggered — zombies slowed!');updateUI();}
ui.start.onclick=()=>{startWave()};ui.volley.onclick=useVolley;ui.frost.onclick=useFrost;
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='q')useVolley();if(e.key.toLowerCase()==='e')useFrost();if(e.key===' '){e.preventDefault();startWave();}});
canvas.addEventListener('click',e=>{let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;let p=pads.find(p=>Math.hypot(x-p.x,y-p.y)<25);if(p)recruit(p);});
function shoot(t,z){arrows.push({x:t.x,y:t.y,tx:z.x,ty:z.y,target:z,speed:390,damage:10+wave,life:1});t.cool=.72;effects.push({x:t.x,y:t.y,type:'shot',life:.18});}
function update(dt){if(running){if(spawnLeft>0){spawnTimer-=dt;if(spawnTimer<=0){spawn();spawnTimer=Math.max(.32,1.0-wave*.035)}}if(spawnLeft===0&&!zombies.length){running=false;gold+=35+wave*10;setMessage('Wave cleared! Bonus gold awarded. Prepare for wave '+(wave+1)+'.');wave++;updateUI()}}
if(frostTime>0)frostTime-=dt;
if(running&&spawnLeft===0&&zombies.length===0) updateUI();
for(let i=zombies.length-1;i>=0;i--){let z=zombies[i];z.hit=Math.max(0,z.hit-dt);if(z.slow>0)z.slow-=dt;let speed=z.speed*(z.slow>0||frostTime>0?.35:1);let a=path[z.segment],b=path[z.segment+1],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);z.t+=speed*dt/len;if(z.t>=1){z.segment++;z.t=0;if(z.segment>=path.length-1){zombies.splice(i,1);hp-=10;shake=10;setMessage('A zombie reached the keep!');updateUI();continue}}Object.assign(z,pathPoint(z));}
for(const t of towers){t.cool-=dt;let target=zombies.filter(z=>dist(t,z)<190).sort((a,b)=>dist(t,a)-dist(t,b))[0];if(target&&t.cool<=0)shoot(t,target)}
for(let i=arrows.length-1;i>=0;i--){let a=arrows[i];if(!a.target||!zombies.includes(a.target)){arrows.splice(i,1);continue}let dx=a.target.x-a.x,dy=a.target.y-a.y,d=Math.hypot(dx,dy),step=a.speed*dt;if(d<=step){a.target.hp-=a.damage;a.target.hit=.12;arrows.splice(i,1);effects.push({x:a.target.x,y:a.target.y,type:'hit',life:.2})}else{a.x+=dx/d*step;a.y+=dy/d*step}}for(let i=effects.length-1;i>=0;i--){effects[i].life-=dt;if(effects[i].life<=0)effects.splice(i,1)}if(hp<=0){hp=100;gold=100;wave=1;running=false;spawnLeft=0;zombies.length=0;towers.length=0;pads.forEach(p=>p.tower=null);setMessage('The keep fell. Rebuild your defense and try again.');updateUI()}}
function draw(){ctx.save();if(shake){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.86;if(shake<.2)shake=0}ctx.clearRect(0,0,W,H);drawGround();drawPath();pads.forEach(drawPad);towers.forEach(drawTower);zombies.forEach(drawZombie);arrows.forEach(drawArrow);effects.forEach(drawEffect);ctx.restore();}
function drawGround(){ctx.fillStyle='#1a3024';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#294637';ctx.globalAlpha=.4;for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.globalAlpha=1;for(let i=0;i<28;i++){let x=(i*173)%W,y=(i*79)%H;ctx.fillStyle='#31553b';ctx.fillRect(x,y,2,2)}}
function drawPath(){ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#0b1711';ctx.lineWidth=64;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#4d6045';ctx.lineWidth=54;ctx.stroke();ctx.strokeStyle='#667054';ctx.lineWidth=2;ctx.setLineDash([10,14]);ctx.stroke();ctx.setLineDash([])}
function drawPad(p){ctx.beginPath();ctx.arc(p.x,p.y,23,0,Math.PI*2);ctx.fillStyle=p.tower?'#34523d':'#a06d3e';ctx.globalAlpha=p.tower?1:.8;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=p.tower?'#78d888':'#e9ac5b';ctx.setLineDash(p.tower?[]:[4,4]);ctx.stroke();ctx.setLineDash([]);if(!p.tower){ctx.fillStyle='#f4c879';ctx.font='bold 19px monospace';ctx.textAlign='center';ctx.fillText('+',p.x,p.y+7)}}
function drawTower(t){ctx.fillStyle='#09150f';ctx.beginPath();ctx.ellipse(t.x,t.y+14,22,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4c7751';ctx.fillRect(t.x-10,t.y-2,20,17);ctx.fillStyle='#8be196';ctx.beginPath();ctx.arc(t.x,t.y-8,10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d5f4a8';ctx.lineWidth=3;ctx.beginPath();ctx.arc(t.x,t.y-9,13,-2.4,.4);ctx.stroke();}
function drawZombie(z){ctx.fillStyle='#09150f';ctx.beginPath();ctx.ellipse(z.x,z.y+12,z.r,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=z.hit?'#f2bf78':(z.slow>0||frostTime>0?'#75b8c0':'#b9695c');ctx.beginPath();ctx.arc(z.x,z.y,z.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#251916';ctx.fillRect(z.x-7,z.y-3,4,4);ctx.fillRect(z.x+3,z.y-3,4,4);ctx.fillStyle='#301b18';ctx.fillRect(z.x-8,z.y+6,16,3);ctx.fillStyle='#111';ctx.fillRect(z.x-16,z.y-z.r-9,32,4);ctx.fillStyle='#de745f';ctx.fillRect(z.x-16,z.y-z.r-9,32*Math.max(0,z.hp/z.max),4)}
function drawArrow(a){ctx.strokeStyle='#f6d99a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(a.x-(a.tx-a.x)*.08,a.y-(a.ty-a.y)*.08);ctx.stroke()}
function drawEffect(e){if(e.type==='frost'){ctx.strokeStyle='#9fe5ef';ctx.lineWidth=4;ctx.globalAlpha=e.life;ctx.beginPath();ctx.arc(e.x,e.y,(1-e.life)*240,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}else{ctx.fillStyle=e.type==='hit'?'#ffd782':'#d9ffaf';ctx.globalAlpha=e.life*4;ctx.beginPath();ctx.arc(e.x,e.y,(1-e.life)*20+3,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
updateUI();requestAnimationFrame(loop);
